module.exports = Object.freeze({

    MY_CONSTANT: 'Some Value',
    ANOTHER_CONSTANT: 'Another Value',

    // Success message constent
    OTP_SUCCESS: 'OTP Generate Successfully ',
    OTP_CORRECT: "Verification successful",
    WELCOME_MSG: "Welcome in Pos App",
    STORED_MSG: "Data Stored Successfully",
    UPDATE_MSG: "Update Successfully",
    LIST_MSG: "Api Data List",
    DELETE_MSG: "Delete Successfully",
    EMPTY_MSG: "Empty List",
    PASSWORD_MSG: "Password Changed Successfully",
    SUBSCRIPTION_MESSAGE: "Your Subscription Will Be Expire After 2 Days",
    SEND_NOTIFICATION_MSG: "Notification Sent Successfully",
    MODULE_ACCESS: "You have permission to access this module",

    // Error message constent
    SOMETHING_WENT_WRONG: "Something Went Wrong!",
    MOBILE_NUMBER_NOT_VALID: "Mobile No is not Valid!!!",
    BLANK_FIELD: "Field should not be blank!",
    OTP_INCORRECT: "Invalid OTP",
    EMAIL_INCORRECT: "Invalid Email",
    PASSWORD_INCORRECT: "Invalid Password",
    OTP_EXPIRED: "OTP EXPIRED, Please send otp again!",
    NOT_EXIST: "Data Not Exist",
    ALREADY_EXIST: "Email Already Exist",
    MOBILE_ALREADY_EXIST: "Email or Mobile Number is Already Exist",
    PASSWORD_NOT_SAME: "New password and Confirm Password Must Be The Same",
    SUBSCRIPTION_EXPIRE: "Please contact wps admin to renew the subscription",
    PERMISSION_DENIED: "You have not permission to access this module",
    PRIVILEGE_ERROR: "Privilege Data Not In Database",

    // Side_Bar Module Names

    /* Admin Side_Bar */
    DASHBOARD_MODULE: "Dashboard",
    PRIVILEGE_MODULE: "Privilege",
    ROLE_MODULE: "Role",
    USER_MODULE: "User",
    COMPANY_MODULE: "Company",
    SUBSCRIPTION_MODULE: "Subscription",
    VENDOR: "Vendor",

    /* Gurukul Side_Bar */
    STUDENT_MODULE: "Student",
    ATTENDENCE_MODULE: "Attendence",
    SUBJECT_MODULE: "Subject",
    CHAPTER_MODULE: "Chapter",
    QUESTION_SET_LIST_MODULE: "QuestionSetList",
    TEST_RESULT_MODULE: "TestResult",
    LIVE_CLASS_MODULE: "LiveClass",
    LIVE_BY_AGORA_MODULE: "LiveByAgora",
    BATCHES_MODULE: "Batches",
    PAYMENT_MODULE: "Payment",
    COURSE_FEE_MODULE: "CourseFee",
    SESSION_MODULE: "Session",
    NOTICE_BOARD_MODULE: "NoticeBoard",
    NOTIFICATION_MODULE: "Notification",
    CHAT_MODULE: "Chat",
    SAMPLE_PAPER_MODULE: "SamplePaper",
    SUBADMIN_MODULE: "SubAdmin",
    SLIDING_BANNER_MODULE: "SlidingBanner",
    NEW_USER_MODULE: "NewUser",
    PREMIUM_COURSE_MODULE: "PremiumCourse",
    RECOMMEND_COURSE: "RecommendCourse",
    RE_COURSE_CHAPTER_MODULE: "ReCourseChapter",
    FREE_VIDEO_MODULE: "FreeVideo",
    FREE_USER_NOTICE_MODULE: "FreeUserNotice",
});